# Global Configuration
encoding: utf-8

# Build settings
markdown: kramdown
permalink: pretty

# GitHub Flavored Markdown
kramdown:
  input: GFM
    
# Site Variables
title: Lee Tze Cheun
tagline: I love bananas. How about you?
email: tzecheun.lee@gmail.com
github: tclee
twitter: tzecheun

# Explicitly specify an empty string because GitHub pages defaults to '/'.
baseurl: ""